# Generated by Django 5.0.7 on 2025-10-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
